version: '3.8'

services:
  api:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: flowerstore
    volumes:
      - ./flower_workshop/bouquets/:/bouquets
      - ./flower_workshop/consultation/:/consultation
      - ./flower_workshop/flower_store/:/flower_store
      - ./flower_workshop/flower_workshop/:/flower_workshop
      - ./flower_workshop/home/:/home
      - ./flower_workshop/orders/:/orders
      - ./flower_workshop/users2/:/users2

