# Generated by Django 4.2.4 on 2023-08-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='type',
            field=models.CharField(choices=[('CL', 'Клиент'), ('FL', 'Флорист'), ('CO', 'Консультант'), ('MA', 'Менеджер')], db_index=True, default='CL', max_length=2, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='user2',
            name='on_vacation',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В отпуске'),
        ),
    ]
