# Generated by Django 4.2.4 on 2023-08-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users2', '0002_user2_type_alter_user2_on_vacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='type',
            field=models.CharField(choices=[('CL', 'Клиент'), ('FL', 'Флорист'), ('CO', 'Курьер'), ('MA', 'Менеджер')], db_index=True, default='CL', max_length=2, verbose_name='Тип'),
        ),
    ]
