# Generated by Django 4.2.4 on 2023-08-16 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bouquets', '0002_bouquet_bouquetflower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('from_delivery_time', models.DateTimeField()),
                ('to_delivery_time', models.DateTimeField()),
                ('address', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Необработанный заказ', 'Необработанный заказ'), ('Готовиться рестораном', 'Готовиться рестораном'), ('Передан курьеру', 'Передан курьеру'), ('Заказ завершён', 'Заказ завершён')], db_index=True, default='Необработанный заказ', max_length=21, verbose_name='Статус заказа')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bouquets.bouquet')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', to=settings.AUTH_USER_MODEL)),
                ('florist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='florist_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
