# Generated by Django 4.2.4 on 2023-08-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_phone_alter_order_address_alter_order_bouquet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UP', 'Необработанный заказ'), ('IW', 'Собирается флористом'), ('DL', 'Передан курьеру'), ('CP', 'Заказ завершён')], db_index=True, default='UP', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
