# Generated by Django 4.2.4 on 2023-08-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='to_delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('FRS', 'Как можно скорее'), ('TW', 'с 10:00 до 12:00'), ('TH', 'с 12:00 до 14:00'), ('FR', 'с 14:00 до 16:00'), ('FV', 'с 16:00 до 18:00'), ('SX', 'с 18:00 до 20:00')], db_index=True, default='FRS', max_length=17, verbose_name='Интервал доставки'),
        ),
    ]
