# Generated by Django 4.2.4 on 2023-08-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_client_alter_order_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(db_index=True, default='D', max_length=80, verbose_name='Имя клиента'),
            preserve_default=False,
        ),
    ]
