# Generated by Django 4.2.4 on 2023-08-16 17:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bouquets_images')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('events', models.ManyToManyField(db_index=True, to='bouquets.event', verbose_name='События')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='BouquetFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flowers', to='bouquets.bouquet', verbose_name='букет')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bouquets.flower', verbose_name='Цветов')),
            ],
            options={
                'verbose_name': 'Цветок в букете',
                'verbose_name_plural': 'Цветы в букете',
            },
        ),
    ]
