# Generated by Django 4.2.4 on 2023-08-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0002_bouquet_bouquetflower'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='recommended',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В рекомендованных'),
        ),
    ]
